export default [
  ["Apple Inc.", "AAPL"],
  ["Pandora", "P"],
  ["Microsoft", "MSFT"],
  ["Alphabet", "GOOGL"],
  ["IBM", "IBM"],
  ["Intel", "INTC"],
  ["Cisco Systems", "CSCO"],
  ["Oracle", "ORCL"],
  ["Facebook", "FB"],
  ["Zynga", "ZNGA"],
  ["HP", "HPQ"],
  ["Walmart", "WMT"],
  ["Tesla", "TSLA"],
  ["Amazon", "AMZN"],
  ["ExxonMobil", "XOM"],
  ["Goldman Sachs", "GS"],
  ["JPMorgan Chase", "JPM"],
  ["Twitter", "TWTR"],
  ["Salesforce", "CRM"],
  ["Macy's", "M"],
  ["Advanced Auto Parts Inc.", "AAP"],
  ["Marathon Oil", "MRO"],
  ["Kroger", "KR"],
  ["Foot Locker", "FL"],
  ["Target", "TGT"],
  ["Bed Bath & Beyond", "BBBY"],
  ["AutoZone", "AZO"],
  ["Under Armour", "UAA"],
  ["Mattel", "MAT"],
  ["Kohl's", "KSS"],
  ["Schlumberger", "SLB"],
  ["TripAdvisor", "TRIP"]
];
