stocks = [
  {'name': "Apple Inc.", 'symbol': "AAPL"},
  {'name':"Pandora",'symbol': "P"},
  {'name': "Microsoft", "symbol":"MSFT"},
  {'name': "Alphabet", "symbol":"GOOGL"},
  {'name': "IBM", "symbol":"IBM"},
  {'name': "Intel", "symbol":"INTC"},
  {'name': "Cisco Systems", "symbol":"CSCO"},
  {'name': "Oracle", "symbol":"ORCL"},
  {'name': "Facebook", "symbol":"FB"},
  {'name': "Zynga", "symbol":"ZNGA"},
  {'name': "HP", "symbol":"HPQ"},
  {'name': "Walmart", "symbol":"WMT"},
  {'name': "Tesla", "symbol":"TSLA"},
  {'name': "Amazon", "symbol":"AMZN"},
  {'name': "ExxonMobil", "symbol":"XOM"},
  {'name': "Goldman Sachs", "symbol":"GS"},
  {'name': "JPMorgan Chase", "symbol":"JPM"},
  {'name': "Twitter", "symbol":"TWTR"},
  {'name': "Salesforce", "symbol":"CRM"},
  {'name': "Macy's", "symbol":"M"},
  {'name': "Advanced Auto Parts Inc.", "symbol":"AAP"},
  {'name': "Marathon Oil", "symbol":"MRO"},
  {'name': "Kroger", "symbol":"KR"},
  {'name': "Foot Locker", "symbol":"FL"},
  {'name': "Target", "symbol":"TGT"},
  {'name': "Bed Bath & Beyond", "symbol":"BBBY"},
  {'name': "AutoZone", "symbol":"AZO"},
  {'name': "Under Armour", "symbol":"UAA"},
  {'name': "Mattel", "symbol":"MAT"},
  {'name': "Kohl's", "symbol":"KSS"},
  {'name': "Schlumberger", "symbol":"SLB"},
  {'name': "TripAdvisor", "symbol":"TRIP"}
];